Settings.ui, panel.js, prefs.js, schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml
Option to show the AppMenu on the right hand side of the panel. This is the tweak I described in #2.
**Edit:** I didn't test this enough. The menu get unhidden after showing the activities overview.
**Edit2:** everything should work
=> Option to add/remove AppMenu

Makefile, appIcons.js, po/es.po
Other changes:
- Add appIcons.js as a file to localize
- In appIcons.js: changed a string, as I can't really translate in Spanish if it's divided into two (same goes for French). Is it ok...?
Even though I tried localizing appIcons, it's not working. It seems Gettext is not applying the translation. I couldn't easily find the reason why, I'll try and see if I can fix it soon!
=> Add Spanish translation

overview.js, prefs.js
Hi,
As discussed, I improved a bit the hotkeys section.
The first commit is actually enough, as it removes the (unnecessary) call to re-write the settings on every boot.
The second commit moves the function to prefs.js, as you suggested we should do.
Let me know what you think!
=> Hotkeys: fix unnecessary rewriting of settings

Settings.ui
Add a space between the tab and the first settings box in fine-tune.
=> Correct top and bottom margin in fine-tune tab

prefs.js
With a laptop screen
Sadly, we can't use a Gtk.Window directly for the pref settings object. If we do so, gnome-shell will draw a Gtk Window +  the gtk Window provided by the extension itself... Otherwise i would have used a Gtk Stack & Gtk StackSwitcher as a custom titlebar for the Headerbar :-)
Anyway this works as expected !
=> Fixes #119

Settings.ui, appIcons.js, overview.js, prefs.js, schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml, taskbar.js
* This hopefully addresses #174 
* Moves the `setShortcut()` function to prefs.js for better performance when enabling
* It also fixes a small problem with the shortcut not being configurable
=> Number overlay: optional transitivity and minor improvements

appIcons.js, stylesheet.css
This adds a number overlay style that can be changed through theming.
The default is specified to white text on black background.
Fixes #182 .
=> Add number overlay style.

panel.js
- Panel barriers are now added back when the extension is disabled.
=> Fix typo preventing proper cleanup.

appIcons.js, taskbar.js, windowPreview.js
This PR enables a small mechanism to enable/disable window previews.
Before this, the window previews were always created, but they were simply not used if the setting was off.
Related to https://github.com/jderose9/dash-to-panel/issues/170. Not a fix, but it helps a lot for people that don't want to use window previews.
=> Window previews

Settings.ui, prefs.js, schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml, windowPreview.js
This PR adds support for middle clicking a window preview to close that window, and right clicking the preview to show the same context menu as right clicking on a window title bar (minimise, close etc).
=> Support middle click on preview to close window and right click to show context menu

appIcons.js, convenience.js, overview.js, panel.js, panelStyle.js, taskbar.js, windowPreview.js
This pull-request fixes some minor JS warnings that occur on gnome-shell 3.26. We faced the same JS warnings in Arc-Menu. For simplicity reasons, we basically defined all classes using 'var' instead of 'const'.
Example JS warnings:
```
Some code accessed the property XYZ on the module ABC. That property was defined with 'let' or 
'const' inside the module. This was previously supported, but is not correct according to the ES6 
standard. Any symbols to be exported from a module must be defined with 'var'. The property 
access will work as previously for the time being, but please fix your code anyway.
```
=> Fix minor JS warnings on gnome-shell 3.26

windowPreview.js
When a popup is destroyed, the window might still emit signals of
title changed, causing crashes in gnome-shell
We're getting multiple crash reports about this in both Ubuntu (https://pad.lv/1714989) and upstream GNOME (https://bugzilla.gnome.org/show_bug.cgi?id=788931)
=> windowPreview: disconnect from window title changes on actor destroy

Settings.ui, panel.js, prefs.js, schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml
Add the feature to move taskbar in center panel, including user settings
Finally there are three choices to dash-to-panel users:
- taskbar in left panel as currently
- taskbar in center panel, centered between the left and the right panel
- taskbar in center panel, centered in monitor without considering left and right panels size
Missing the translation of new pref.
And it would be maybe better to use "if" loops rather than logical operations with booleans "ctb" and "cim" in the calculation of allocation size in panel.js
=> Add the feature to move taskbar in center panel, including user settings

Makefile, Settings.ui, appIcons.js, img/highlight_bg.svg, img/highlight_stacked_bg.svg, overview.js, panel.js, prefs.js, schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml, stylesheet.css, taskbar.js, windowPreview.js
Hey Jason! First, thanks for the extension, really enjoying it. I worked on the ungrouping of the icons and some little bug fixes. Let me know if you need more info and sorry for the big review :)
Charles
New features
- ungroup aplication instances, while keeping them grouped by application
- when ungrouped, display the window titles and allow the customization of their font-size and width
- when ungrouped, optionally have the favorite application icons serve as launchers
- customize the focused application indicator's color and opacity
Bug fixes
- fix icons not showing up immediately when lauching an application
- fix message "g_signal_handler_disconnect: assertion 'handler_id > 0" occurring when destroying an icon
- fix message "st_widget_get_theme_node called on the widget [# …
=> Add option to ungroup the application instances and show their window titles

Settings.ui, panel.js, prefs.js, schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml
Hey Jason! a small improvement for people like me (and #305) having a 2 monitors setup with the "show desktop button" being on the edge between the 2 monitors. I know that this issue wasn't flagged as "help wanted", but it seemed like an easy fix that shouldn't break anything else. Thanks!
=> Add option to set the "show desktop button" width

taskbar.js
Hey Jason! Seems like the older versions of gnome aren't supporting the array findIndex method. I checked in ubuntu gnome 16.04 (gnome-shell 3.18.5) and it is causing an issue with the ungrouping modification (as reported in #302). I added a simple polyfill to have it working again. Sorry about that, I should have tested on more distro/versions. Thanks!
=> Add a polyfill for the findIndex method

panel.js, taskbar.js
Hey Jason! Another day, another fix concerning the older gnome-shell versions (Arc-Menu search mentioned in #302)... I could reproduce it on gnome 3.18.5. Don't ask me to explain what was happening with this :) but it should be good now, I think.
Also, the modification in panel.js is another fix for a "doesn't always return a value" log message. 
Thanks!
=> Fix compatibility of the apps ungrouping with older gnome versions

Settings.ui, po/es.po
Hey @jderose9 !
Here is the PR for v12. I added a patch to remove the `translatable` property for numbers. I don't know if this was really intended. Feel free to ignore the second commit if it was the case!
=> Spanish translation for v12

appIcons.js, taskbar.js, windowPreview.js
Hey Jason! I investigated the warnings received after upgrading to gjs 1.50.4 (#338) and found out that the appicon's ondestroy function isn't called when the extension is disabled. This commit fixes that and also removes a timer that could end after the windowpreviews are destroyed (also reported as a warning by the latest gjs).
Now, on my end, the only warnings I get from gjs is from tweener.js and this one is [out of our hands](https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1747566)
Sorry I couldn't fix that in time for v12 :(
Thanks
=> Fix for gjs 1.50.4 warnings

windowPreview.js
Hey Jason, I found a visual problem with one of the recent modifications for gjs 1.50.4 :( 
When many application instances are grouped in a single popup menu, closing a window using its X button doesn't immediately resize the window preview popup menu (it is resized when hovered next). 
Here is the fix for it, without reintroducing the originally fixed gjs warnings. Sorry about that and thanks again!
=> Disconnect the window preview thumbnail from its window

appIcons.js
Behaviour that might be unexpected:
- long-pressing a background application opens the popup menu, but still activates/starts the application. Only activating the application on TOUCH_END/TOUCH_CANCEL turned out to work only sometimes on my system, I'll do some further tests on that.
- dragging via touchscreen is completely disabled for now, as it gets confused with the mouse, bugs around and in the end breaks everything (as said in the issue, up to a frozen system).
=> Fix touchscreen behaviour for taskbarAppIcon (#223)

windowPreview.js
Apps which behave irregularly upon window preview hover have been separated into a blacklist and Remmina has been added to the blacklist. This is an extension to the fix for Issue #212.
=> Created app hover blacklist & added Remmina to it

Makefile, Settings.ui, appIcons.js, convenience.js, intellihide.js, panel.js, prefs.js, schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml
Hey Jason, here is the intellihide behaviour for #41, without the conflicts :)
I feel like I tested quite a bit, but mostly on a single screen (I'm currently travelling with a laptop only). I was able to test with a borrowed secondary screen and everything seemed fine, but I would't call that "extensive". 
There is an incompatibility with TopIcons plus where the legacy tray icon "texture" doesn't move along the panel, but it only happens when the TopIcons are first placed on the default gnome top bar, then dash to panel is enabled. If gnome-shell is started with dash to panel enabled, everything is fine. I think this should be fixed on the TopIcons plus side (not maintained anymore) since its icon placement results in the same problem on the default gnome top bar (unnoticeable, since the …
=> Add intellihide feature

intellihide.js
Hey Jason, this is a fix for issue #356, I was wondering when this "desktop" windowtype would show up. Looks like the desktop icons must be shown :)
=> Ignore the desktop when the "Show icons" option is enabled

intellihide.js
Hey Jason, small fix (probably) for the syntax error discovered in #357. I also reseted an indicator controlling the panel hiding delay, so that it only applies when the user hovers out of the panel after revealing it. Thanks!
=> Fix syntax error reported by older gnome-shell versions

intellihide.js
Hey Jason! As discussed in #360, here is another small addition to make sure the panel always is visible when in the overview. Thanks.
=> Reveal the panel in overview

intellihide.js
Hey Jason, here are more fixes for the overview, as discussed in #360. With this, the mouse at the edge of the screen has no effect while in overview and the panel now uses the same animation timing as the workspaces bar (you were right, looks much better :) Thanks!
=> Fix the intellihide animations when entering/leaving the overview

extension.js, intellihide.js
Hey Jason, I'm looking at Ubuntu 18.04 and I noticed an error when disabling the dock (disabling it causes a lot of errors, but on the ubuntu-dock side of things). I also ignored the intellihide update delay when exiting the overview. Thanks.
=> Add missing reference to GLib

intellihide.js
Hey Jason, I just noticed a small issue with the intellihide. When you are in "hide from focused window" mode and there is a fullscreen window in the background, if you resize a foreground window over the panel (by dragging one of its bottom corners), the panel hides and then reveal itself again. This PR fixes that. Thanks!
=> Ignore window resizing while in fullscreen mode

po/zh_CN.po
As requested in #385 , this PR would refresh Simplified Chinese translation ( `zh_CN` translation) for v14.
=> po: Update Simplified Chinese translation for v14

panel.js
Hello,
Because I'm using both _Dash to Panel_ and _No Title Bar_, I can have very long leftBox while I'm in CENTEREDMONITOR option. So, when it's so long, when leftBox reaches centerBox, the centerBox is moved to the right to let leftBox occupies all the space it want to. My centerBox, with my dash in panel, can even be hidden by the rightBox.
To avoid this, I fix centerBox in its place when CENTEREDMONITOR option is checked.
Before:
After:
=> don't move when CENTEREDMONITOR

extension.js
I was running into a stateObj undefined error on my local Ubuntu installation. Added this check in to prevent exceptions.
=> Fix ubuntuDock.stateObj error

Settings.ui, appIcons.js, prefs.js, schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml
Currently when ungrouped, application titles are displayed with the default font weight.
This PR adds a combo box to the settings menu for changing of the font weight to user's preferences.
Supported values for font-weight are:
- **`inherit` (the default)**;
- `normal`;
- `lighter`;
- `bold`;
- `bolder`.
The default value is `inherit`, which keeps the font weight of the active theme.
=> Allow changing of font weight of ungrouped application titles.

po/zh_CN.po
This commit finishes `zh_CN` (Simplified Chinese) translation of dash-to-panel v17.
=> po: Update zh_CN translation for v17 release

appIcons.js
When using multiple physical monitors and disabled multi monitor in DTP, the focused application on the secondary monitor does not have a highlight on the icon in the panel.
This checks to see if multi monitor setting is enabled, before checking if the current monitor is active.
=> Only check monitor index if multi monitor is enabled.

Settings.ui, appIcons.js, prefs.js, schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml, utils.js
This adds the "use dominant color" functionality seen in [dash-to-dock](https://github.com/micheleg/dash-to-dock/blob/master/appIconIndicators.js#L951). 
Screenshot of the feature in action:
I added a switch in the prefs dialog. Activating either "Icon Dominant" or "Override Theme" will deactivate the other switch. Deactivating both will result in using the theme default color.
Screenshot of prefs dialog:
=> port DominantColorExtractor from dash-to-dock

panel.js
I'm using Gnome 3.22.2 (Debian 9). Here, the latest code on `master` fails with some syntax errors. This PR is a fix for this.
=> fix error on Gnome 3.22.2

panel.js, progress.js
Resolves the syntax errors found on Debian 9 with GNOME 3.22.2 reported in #885.
=> Fix syntax errors

appIcons.js, schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml, utils.js
Proposing a partial fix to #847 by calling which on each command before adding it.
I ran into #847 on a vagrant ubuntu box I use as a dev environment (ubuntu server + ubuntu-gnome-desktop) which does not install a few of the options.
This change does not solve customizing the menu entries, but at least no invalid options are added.
=> AppsIcon Menu only shows existing apps

appIcons.js, stylesheet.css
Here's a better fix for #911 that only touches stylesheet.css. Looks like we only need to set the background on the overview-icon. I checked this against the Deepin and Arc shell themes and verified the transparency.
=> Override show-apps background for transparent icons

Settings.ui, panel.js, prefs.js, schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml
This PR adds a toggle to show/hide the workspace switch popup when scrolling on the panel to change workspace.
=> Toggle workspace switch popup

panel.js, stylesheet.css
These changes add light theme support for desktop button.
The dark themes will remain the same but the light ones will now receive a dark line based on the color offset that is used to original color. (light: `55,55,55,0.2` / dark: `200,200,200,0.2`).
I keep the `.2` (20% of opacity) because the original is that, but maybe it could be too transparent for some themes.
It detects if it's dark theme or light one based on brightness of the background color, the result is a int between 0 (total black) and 255 (total white), I choose the 128 to be the divisor between dark and light.
I couldn't use the `backgroundColorRgb` since it wasn't returning the expected results, but I find the variable: `currentBackgroundColor` which works, but I had to transform it from string.
I didn't find a way to …
=> add light theme support for desktop button

Settings.ui, prefs.js, schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml, windowPreview.js
These changes add the option to change the preview window icon size:
16px:
disabled:
=> add option to change the preview window icon size

Settings.ui
The GtkColorButton “show-editor” property was introduced in Gtk 3.20 so it make preferences non-openable in GS 3.18.
Fix cfab668
Related to #1101
@hlechner
=> Settings.ui: remove show_desktop GtkColorButton property

overview.js
dragging overview to switch workspace results in closing overview if the pointer is hold before release
check [before](https://streamable.com/rj0s68) and [after](https://streamable.com/casnjz) the patch
=> Fix workspace navigation when dragging overview

appIcons.js, taskbar.js
Dragging an icon from the applications view to the taskbar gives the error `appIcon.getIconContainerStyle is not a function`. This PR fixes this and makes the drag and drop work again.
Tested with GNOME Shell 3.36.6 (Arch Linux)
=> Fix drag and drop from the applications view to the taskbar

Makefile, Settings.ui, appIcons.js, panel.js, panelManager.js, panelPositions.js, panelSettings.js, prefs.js, schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml, taskbar.js, utils.js, windowPreview.js
Set the length of the panel according to a specified percent value, so
it can span only part of the screen edge.
Position the panel at the start, middle, or end of the screen edge, as
specified.
Tests okay with multiple monitors.
May also satisfy home-sweet-gnome/dash-to-panel#726
=> Display panel along percent of screen edge

appIcons.js, panelManager.js, progress.js, taskbar.js
When an app icon is marked as "urgent" (using the [Unity Launcher API](https://wiki.ubuntu.com/Unity/LauncherAPI)), this code animates the icon until the app is focused/clicked on again in order to draw attention to it.
Some apps that set the "urgent" property include the Software Updater in Ubuntu (when the system needs to restart after an update) and [Teatime](https://snapcraft.io/teatime) (after the timer rings) like in this clip: https://i.imgur.com/hJewEcj.mp4
(Code adapted from the Dash to Dock extension)
=> Animate app icons when urgent property is set

Settings.ui, appIcons.js, prefs.js, schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml, stylesheet.css, taskbar.js
There is 3 animation types but more may be added easily in the future.
A new TaskbarItemContainer class extends DashItemContainer.
Unfortunately, the clone actors used for the animation are not reactive. So, if the pointer follows the animated clone and leaves the taskbar allocation, it is dropped. This limits the possible translation.
See details in commit logs.
I think it closes #733.
=> Appicon animation on hover

taskbar.js
In an effort of making the extension more coherent with gnome-shell, I propose this change that is coherent to how Gnome 3.38 manages the drag and drop in the applications view. Basically in Gnome 3.38, when dragging an icon, the icon starts following the cursor and then it creates "empty spots" in relation where the cursor is to show where the app will be placed.
The extension already makes the icons less opaque when using drag and drop, so just setting them to be invisible does the trick.
I think that this change also makes the drag and drop cleaner.
=> Hide appIcon in the taskbar when in drag and drop

panel.js
Hello!
After updating to the latest version of the extension I noticed that there was a strange gap between the top gs-panel and the extension's panel. 
Looking through the code I found this [line](https://github.com/home-sweet-gnome/dash-to-panel/blob/6a76c9e9145aa0e28994721421a15dabe37b2be2/panel.js#L865),
```js
anchorPlaceOnMonitor = (this.monitor.height - h) / 2;
```
which I assume is equivalent to,
```js
offset = (fullHeight - panelHeight) / 2
```
However, when the gnome-shell's top-panel is present, `fullHeight` i.e. the full available height is actually less than `this.monitor.height`, which is possibly why the offset is a bit off.
In this PR I added the `gsTopPanelOffset` as part of the calculation, which should hopefully resolve the issue. 
I can confirm that the fix is working …
=> Fix offset when gnome-shell top panel is shown

prefs.js
There was a merging error for panel_size_scale_value_changed_cb with the gnome40 merges, this PR fixes it.
=> Fix merging errors for panel_size_scale_value_changed_cb

Settings.ui, prefs.js
- format-value callback for GtkScale can no longer be set via .ui file, so set the callbacks directly in the prefs.js via set_format_value_func.
- also fixed app icon animation options dialog layout
=> Format value callbacks, app icon animation options dialog layout

panelManager.js
Fixed a bug that caused the panel to disappear after locking the screen while fullscreen content is playing  (#1236).
It appears that setting the panelBox visibility to be false if fullscreen content is on top while creating the panel (when unlocking the screen in this case) is stopping the panel from initialising fully.
If we always set the panel to be visible but hide it immediately afterwards if fullscreen content is on top, we fix this issue while keeping the expected behaviour (i.e. not drawing the panel on top of fullscreen content).
I have tested that this fix works in Gnome Shell 3.38.4 and Gnome 40
=> Fix panel disappearing after screen unlock with fullscreen content

prefs.js
Size the toplevel dialog instead of the notebook.
=> Make the preferences dialog resizable

prefs.js
The "Show Applications options" dialog creates a new file chooser every time it is opened. But it is not destroyed, so the file chooser instances multiply. This is fixed by this PR.
=> destroy show apps file chooser dialog when show apps dialog is closed

appIcons.js, metadata.json
AppIconMenu got renamed to AppMenu in Gnome 41, with this PR it will work again on gnome 41.
=> Gnome 41 compatibility

extension.js
Use startInOverview flag, so hide overview will work in Ubuntu again.
The flag was added https://salsa.debian.org/gnome-team/gnome-shell/-/merge_requests/52 for Ubuntu.
=> Use startInOverview flag to hide overview on startup (Ubuntu only atm)

panel.js
A change of function name change for the scroll handler caused this issue in this commit:
https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1566/diffs
Fixes #1374
=> Fix volume control on scroll for Gnome 40+

appIcons.js, metadata.json, panel.js
Fix right click menus on panel + icons in panel (#1488):
Currently these changes break compatibility to gnome 40.
=> Updated AppMenu, PopupMenu handling for gnome 41

utils.js
The `.get_names()` method only exists for `Gio.ThemedIcon` instances. This avoids spamming the journal with errors like the following:
```
JS ERROR: TypeError: iconTexture.get_names is not a function
_getIconPixBuf@/home/aperez/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js:846:61
_getColorPalette@/home/aperez/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js:865:27
_getFocusHighlightColor@/home/aperez/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:1089:31
_setIconStyle@/home/aperez/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:606:39
_displayProperIndicator@/home/aperez/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:703:14 …
```
=> Use .get_names() only on Gio.ThemedIcon instances

appIcons.js
Fixes the quit from taskbar behaviour with ungrouped windows (only close the selected one) and also the text for grouped windows (i.e. Quit 3 windows). (#1513  #1548)
=> Fix quit from taskbar behaviour and text

prefs.js
Bind does not seem to work with a lambda function (was Land.bind before), use this._preferences directly.
=> Fix change of panel thickness in prefs

Makefile
Resolve #1415 
- generate POT file with non asci symbols (use UTF-8)
- change newline symbol in POT file (by sed)
=> Fix makefile POT file generation

Settings.ui
The 'Toggle single / Cycle multiple' option was added by https://github.com/home-sweet-gnome/dash-to-panel/pull/1195, but for some reason only to the shift+click action. This adds it to the other click methods (click, middle click, shift+middle click)
=> Add 'Toggle single / Cycle multiple' option to all click methods

Settings.ui, panel.js, prefs.js
I found it a little weird that the setting for the notification badge is hidden in the schema file without an appropriate UI to toggle it. 
Before this PR, to toggle the notification badge one would have to:
1. Modify the `schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml` file at `progress-show-count` key.
2. Rebuild the schema via `glib-compile-schemas schemas`
3. Re-log.
With this, PR one just has to toggle this switch in the `Behavior` tab:
On:
Off:
=> Toggle for notification counter badge

Makefile, desktopIconsIntegration.js, panelManager.js
When Dash to Panel is in autohide mode, Desktop Icons NG (DING) can't know how much space the dock need, so icons can be put below the panel and become inaccessible. 
This is a generic fix for this. It adds a class (DingIntegration) that allows other extensions to communicate with Ding and any other extension that would need to know variable margins to avoid to put elements there.
The other part is at https://gitlab.com/rastersoft/desktop-icons-ng/-/merge_requests/196
=> Desktop Icons NG integration

Settings.ui
Replace `https://github.com/jderose9/dash-to-panel` with updated GitHub repository link `https://github.com/home-sweet-gnome/dash-to-panel` in the **About** tab.
=> Update GitHub repository link

po/pl.po
When right-clicking icon on panel the Polish translation for "Quit" is different and too verbose than what I get in dash.
Gnome dash (activities view):
Dash to Panel:
=> Update Polish translation to correspond with Gnome

appIcons.js
Launching an application should perform the default action for that application instead of the "open new window" action when it's not running.
=> Change first launch action fixes #1622

po/pt_BR.po
Hi, thanks for this nice extension, it's very useful. I found some incorrect translations for the Applications button. I opened this PR to help make the extension better. I hope it helps. Thanks.
=> Fix some pt_BR translations for Applications button

po/it.po
"make" can't complete due to the missing quote symbol in the msgstr
```
msgfmt -c po/it.po -o po/it.mo
po/it.po:1234:9: syntax error
po/it.po:1234: keyword "es" unknown
po/it.po:1235: end-of-line within string
msgfmt: found 3 fatal errors
make: *** [Makefile:66: po/it.mo] Error 1
```
=> Fix build failure (after PR #2006)

appIcons.js, prefs.js, schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml, stylesheet.css, taskbar.js, ui/SettingsStyle.ui
Now we can change the style of app icons to symbolic. Closes one of the requested features in issue #307.
=> Add setting for changing app icon style to symbolic

desktopIconsIntegration.js
These changes remove some dependencies, and ensure that it works on Gnome46, where there is a change in the ExtensionState names.
=> Update desktopIconsIntegration to the last version

taskbar.js
fix hscroll.get_adjustment and vscroll.get_adjustment function deprecated warning in system log every time scroll in panel
=> fix function deprecated warning

appIcons.js
The old command was removed from GNOME 47:
https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3456
=> Update command for Extensions app

po/es.po
**Descripción:**
Este Pull Request incluye mejoras y correcciones en las traducciones al español de la extensión Dash to Panel. Los cambios fueron realizados directamente en el archivo es.po y luego se generó el archivo es.mo correspondiente para que la extensión funcione correctamente en el sistema.
***Cambios realizados:***
Traducción de la cadena con pluralidad "Quit %d Window(s)" para manejar adecuadamente el conteo de ventanas. Ahora se traduce como "Cerrar %d ventana(s)".
***Motivo de los cambios:***
El propósito de estas mejoras es asegurar que todas las cadenas del menú y opciones de Dash to Panel sean claras y correctas en español, especialmente en las situaciones con pluralidad de ventanas.
**Pruebas realizadas:**
Verifiqué que la extensión se muestra correctamente en español …
=> Add Spanish translations for "Quit Window" and "Quit Windows"

appIcons.js, schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml, ui/SettingsStyle.ui
This adds 'Grayscale' option to the 'Icon Style' dropdown on the Style tab of setting for the extension.
I found all the colors distracting when the icons are always in the panel.
It will add a desaturate effect to the icons before they are displayed.
Color is visible on hover and animation.
Cheers
=> Add option in setting to change all icons on panel to grayscale... 

Makefile
Sets the correct paths to JS files, as previously `make potfile` failed with error.
> make: *** No rule to make target 'prefs.js', needed by 'po/dash-to-panel.pot'.  Stop.
=> Makefile: Fix potfile generation

Makefile
System-wide installation should install locale/ and gsettings schema in system directory. This enables override supports, locale stripping and not shipping pre-compiled schema file.
Cherry-picked-from: micheleg/dash-to-dock@4dd565dad920ce44303635b550a39bbdbe34fb70
=> Makefile: support system-wide installation.

src/panel.js
After a Gnome update, the Dash-to-Panel plugin showed ellipses for time in vertical mode. Analysis revealed the hour - minute separator changed to an ASCII colon.
To fix this, I updated the code's delimiter to the ASCII colon. Post - modification, time display is back to normal, ensuring users see accurate time in vertical mode post - update.
=> Vertical panel time ellipsis post-Gnome update (ASCII colon split)

src/extension.js, src/panelSettings.js
This patch ensures that the panel settings cache is cleared when disabling the extension as well as when initializing panel settings.
This fixes an issue where settings were sometimes overwritten by stale values in the adjustMonitorSettings function, as well as freeing up memory while the extension is disabled.
The old cache would persist after disabling the extension and would remain if the extension was re-enabled, so if some of Dash to Panel's gsettings were changed while the extension was disabled, they would be overwritten by stale cache values when re-enabling the extension as the cache only gets updated while the extension is running.
=> Fix cache bug
