Settings.ui
overview.js
prefs.js
schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml

`<Sup> + Num` to activate/launch apps
@jderose9 Thanks for taking a look!

Implement hotkeys for dash-to-panel.

---

po/pt_BR.po

Dash to panel in pt_BR

---

Settings.ui
overview.js
prefs.js
schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml
taskbar.js

This is very similar to what was done in dash-to-dock with @micheleg's help.
Thoughts?

Implement overlay numbers for the hotkeys

---

po/cs_CZ.po

Hi, 
I've created cs_CZ translation. Would you like to add it?
Cheers
Milan

Adding cs_CZ translation

---

po/cs_CZ.po
po/es.po
po/fr.po
po/pt_BR.po

This PR adds French translations.
Other `.po` files are changed because I did a `make mergepo` before beginning to translate.

Add French translation

---

metadata.json

Tested on Ubuntu 17.04. Haven't found any bugs.
Screenshot: [screen](https://i.imgur.com/3T3N2L9.png)

Support for Gnome 3.24

---

po/hu.po

Hi @jderose9 
Here is the Hungarian translation for dash-to-panel GNOME extension.

Added Hungarian translation

---

README.md
po/zh_CN.po

Thanks for your awesome extension. I would like to provide with translation for Simplified Chinese here.

Add Simplified Chinese translation

---

README.md
po/uk.po

Hi @jderose9 !
Here's the Ukrainian translation for Dash To Panel.
Cheers!

Added Ukrainian translation

---

Settings.ui
prefs.js
schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml
windowPreview.js

This branch adds window peeking feature.

Enhancement 97

---

Settings.ui
prefs.js
schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml
taskbar.js

Backport hide favorite option

---

windowPreview.js

I've used this fork for the past couple of days and have noticed no ill-effects, no flickering, but it still fixes the problem with virtualbox.

Fixes issue #212

---

panel.js

Hi!
Following the new upstream dynamic transparency feature, here is a fix for the case where the panel is at the bottom.
I'm essentially injecting a slightly modified version of the `updateSolidStyle` function.

Transparency: dynamic transparency for bottom position

---

appIcons.js
convenience.js
panel.js
windowPreview.js

This pull-request fixes a few bugs that I discovered in the systemd log. For more details see the commit messages :-).
I'm think the commit 5a76f1212f5e16c614d4f32ede642fd02d400b6e removes dead or broken code. In other words, it does not make sense to disconnect a signal whose id (i.e., _stateChangedId) is not already known or defined. Or maybe I' oversee something.

Fix a few bugs

---

README.md

@jderose9 
This pull request revamps the dash to panel landing page, it includes new artwork and the rearrangement of the main page.
Also included is the artwork broken into two sections PNGs and SVGs (raw files) and also the previews gif file I’ve also designed two logos one dark and another light all packaged in the zip file, link is below, the artwork can be released under any license you see fit. also if you want to tweak anything feel free.
Link - [dash-to-panel-artwork.zip](https://github.com/jderose9/dash-to-panel/files/1423773/dash-to-panel-artwork.zip)
Signed-off-by: LinxGem33 < Andy C >

Revamped Dash to Panel Landing page #270 

---

po/uk.po

This PR brings minor fixes and improvements to Ukrainian translation.

Improve Ukrainian translation

---

taskbar.js

Hey Jason, here is the small fix for the delay when the apps are grouped (#207). I also extracted a common filter to get the icons on the taskbar. Thanks again!

Bind the icons visibility to the displayed windows even when the apps are grouped

---

po/zh_CN.po

This commit would update `zh_CN` (Simplified Chinese) translation for v12 release of dash-to-panel (Folow-up of #323)

po: Update Simplified Chinese transltion

---

po/cs_CZ.po

Updated Czech translation - v12

---

appIcons.js

Hey Jason, here is a small fix for #346. I was experiencing the same issue, but it wasn't really a problem for me so far. Thanks!

Use the new-window action when launching a new application instance

---

Settings.ui
appIcons.js
prefs.js
schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml

Hey Jason, this is the addition of a setting to select a custom "Show Applications" icon, as asked in #43 and #349. Thanks!

Add the option to select a custom Show Applications icon

---

panel.js

Hey Jason, I could reproduce the issue mentioned in #352 with the "flat-remix-dark-miami" theme on gnome 3.26.2. Once again, removing styles asynchronously seems to alleviate the problem. I do believe that the problem is on the theme side though since now, instead of crashing the shell on the `_st_create_shadow_pipeline_from_actor` call, the following message is logged:
`Ignoring excess values in shadow definition`
Thanks

Fix for dynamic transparency crash under certain themes

---

Settings.ui
prefs.js
schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml
stylesheet.css
windowPreview.js

Hey Jason, here is a small addition following some ideas in #27. This PR adds some settings to customize a bit the window previews (dimensions, padding and hide the window titles). Thanks!

Window preview settings

---

intellihide.js

Hey Jason, here is a small fix to reset the intellihide's reveal mechanism when the user changes it's primary monitor (#379). Would you mind checking if it works for you? as I don't have 2 physical monitors right now (I only tested on virtualbox with some "virtual screens"). Thanks!

Primary monitor change

---

po/cs.po

https://github.com/home-sweet-gnome/dash-to-panel/issues/385

v14 - cs tranlation update

---

po/ru_RU.po

Fixed Russian translation typo.

Fixed russian translation.

---

po/tr.po

tr.po: Fix missing quote

---

panel.js

I'm not sure if it is correct, just CTRL + C, CTRL + V this ⬇
https://github.com/micheleg/dash-to-dock/pull/859/

Avoid repainting an unchanging dock.

---

po/it.po

Add it.po translation as Italian translation

Italian translation

---

po/cs.po

Czech translation - v17

---

po/fr.po

This adds missing French translations, and updates some of the existing ones.

Update French translations (v17)

---

po/ru_RU.po

Adds missing Russian translations and updates some of the existing ones.

Update Russian translation for v17

---

po/tr.po

Adds missing Turkish translations and updates some of the existing ones.

Update Turkish translation for v17

---

Settings.ui
appIcons.js
schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml

If running application has more than 1 window don't close the window preview and do nothing. If running application has 1 window minimize or activate. This behaviour is more similar to Windows.

Added new option to clicking on the icon of a running application

---

po/zh_TW.po

add zh_TW translation. (OpenCC)

---

po/cs.po

Hi @jderose9 
updated po/cs.po as requested.
Cheers
Milan

Updated CS translation

---

po/zh_TW.po

Finally I finished the translation.
Many thanks to @pan93412 for reviewing and improving this translation! QAQ

update zh_TW translation

---

po/ru.po

translation added, paragraphs 185-194

Updated Russian translation, ru.po

---

po/zh_CN.po

As requested in #756 , this pull request updates the `zh_CN` translation.

Full Simplified Chinese translation for dash-to-panel v24

---

po/cs.po

https://github.com/home-sweet-gnome/dash-to-panel/issues/756

Updated po/cs.po 

---

po/es.po

Hi. I fixed a couple of misspellings in the Spanish translation, please review. And thanks for you work, Dash to Panel is the only thing that keeps Gnome usable for me!

Fix Spanish translation

---

Settings.ui
panel.js
prefs.js
schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml

add option to change Show Desktop Button line color

---

Settings.ui
appIcons.js
schemas/org.gnome.shell.extensions.dash-to-panel.gschema.xml

Includes a new click action option to cycle between windows when there is more than 1 window opened, and to Toggle when there is only one.

Add click option to Toggle single / Cycle multiple

---

po/fa.po

Hi.
Thanks for making this extension.
I tried to translate part of this extension into Persian, but it has not been completed yet.
I hope it is useful, I will try to complete this translation.

add persian translate

---

appIcons.js
intellihide.js
metadata.json
overview.js
panel.js
panelManager.js
prefs.js
taskbar.js
transparency.js
utils.js

Makes dtp work with gnome 42 and keeps backwards compatibility with gnome 41.

Support for gjs 1.71.1 and gnome-shell 42

---

po/pt_BR.po

Hello,
Using the extension, I verified that several fields were not translated. So I decided to help, as a result I'm sending an update of the "Brazilian Portuguese" translation.
Actions taken: 
- Fixed some "strange" translations (robot style)
- Added new fields 
- Updating file and line indicators 
PS: Due to the size of the other translations, there are pending fields, I will work to update them all next.  
PS[2]: Thank you for this amazing extension! ;D

Updating translation "Português Brasil"

---

appIcons.js
po/ko.po

I translated essential things for use this extension and translatable text added.

Add Korean Translation and Update appIcons.js

---

metadata.json
prefs.js
utils.js

Adds compatibility for gnome 44, tested backwards compatibility with gnome 43.

Initial gnome 44 support

---

taskbar.js

Fix getAppFromSource call

---

appIcons.js
desktopIconsIntegration.js
extension.js
intellihide.js
overview.js
panel.js
panelManager.js
panelPositions.js
panelStyle.js
prefs.js
progress.js
proximity.js
taskbar.js
transparency.js
utils.js
windowPreview.js

This should address all (most?) of the review requirements set by @justperfection.

GNOME 45 Review

---

appIcons.js

- fix redeclaration of import Gio

fix: correct a typo caused redeclaration of import Gio

---

appIcons.js
extension.js

This makes the terminal command configurable.

Read default terminal from settings

---

appIcons.js

Log:
```bash
anduin@u-real:~$ journalctl -f -o cat /usr/bin/gnome-shell
JS ERROR: ReferenceError: _appendItem is not defined
_appendList@/home/anduin/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:1867:13
updateItems@/home/anduin/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:1782:18
MyShowAppsIconMenu@/home/anduin/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:1748:14
createMenu@/home/anduin/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:1688:26
_onButtonPress@/home/anduin/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js:908:38
[
"/opt/missioncenter.appimage"
] [
"Open task manager"
]
appending list
appending item with …
```

Update appIcons.js to fix an issue that context menu may crash

---

stylesheet.css

Complement 632d3bdcfcb3a49439aed6b0544bb93259d86777 by also removing the background of the Applications icon.
Resolve #2118.

Remove Yaru show-apps icon background

---

po/sk.po

New strings translated and fixed some old translations

Update Slovak translation

---

po/pl.po

Still in translation are missing some strings, like:
#~ msgid "Behavior"
#~ msgstr "Reakcja"
#~ msgid "Style"
#~ msgstr "Wygląd"
#~ msgid "Action"
#~ msgstr "Działanie"
#~ msgid "Fine-Tune"
#~ msgstr "Dostrajanie"
#~ msgid "Position"
#~ msgstr "Pozycja"
#~ msgid "About"
#~ msgstr "Informacje"
Above strings are for bottom menu of settings.
#~ msgid "Icon style"
#~ msgstr "Styl ikony"
#~ msgid "Normal"
#~ msgstr "Normalna"
#~ msgid "Symbolic"
#~ msgstr "Symboliczna"
This is for animating preview of opened programs
So please add into master file

Fixed Polish translation

---

po/tr.po

1. Updated Turkish translation.
2. Added missing sentences to tr.po file.

Updated Turkish translation.
